// Auto-generated by Supabase CLI: supabase gen types typescript --local > types/database.ts
// Run this command after applying migrations to regenerate.
// Placeholder until migrations are applied.
export type Database = {
  public: {
    Tables: Record<string, unknown>
    Views: Record<string, unknown>
    Functions: Record<string, unknown>
  }
}
